---
## Author
author:
  name: Аль-хадри Мохаммед Фуад Мохаммед Хамуд
  email: 1132255653@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Миклухо-Маклая, 21

## Title
title: "Шаблон отчёта по лабораторной работе №10 "
subtitle: "Архитектура компьютера и операционные системы"
license: "CC BY"
---

# Цель работы

Познакомиться с операционной системой Linux.Получитьпрактические навыки рабо
тысредактором vi,установленным по умолчанию практически во всехдистрибутивах

# Задание
- Создание нового файла с использованием vi
- Редактирование существующего файла

# Теоретическое введение


В большинстве дистрибутивов Linux в качестве текстового редактора по умолчанию
устанавливается интерактивный экранный редактор vi (Visual display editor).
Редактор vi имеет три режима работы:
– командный  режим— предназначен для ввода команд редактирования и навигации по
редактируемому файлу;
– режим вставки—предназначен для ввода содержания редактируемого файла;
– режим последней(или командной) строки—используетсядля записи изменений в файл
ивыхода изредактора.

# Выполнение лабораторной работы

Описываются проведённые действия, в качестве иллюстрации даётся ссылка на иллюстрацию ([рис. @fig-001]).

![V Сольвеевский конгресс (1927) «Электроны и фотоны»]

# Выводы

Здесь кратко описываются итоги проделанной работы.

# Список литературы{.unnumbered}

::: {#refs}
:::
